### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by embn** [xavdid/epub-wordcount#21]
I want to use this program in CLI, how do I install it?

**Comment by xavdid** [comment]
Ah, sorry about that! Can't believe I forgot to include that in the readme. 

It's a JS tool, so you use one of the JS package managers:

`npm i -g epub-wordcount`

If your node path is set up correctly, you'll be able to invoke it on the command line. There's more information about getting global commands to be found [here](https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found).

**Comment by embn** [comment]
Ah

**Comment by embn** [comment]
Ah very good. I figured out how to run it with nodeJS, but it's good to be able to properly install it, thanks.

**Comment by xavdid** [comment]
No problem! I've added a section to the readme: https://github.com/xavdid/epub-wordcount#installation
